// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB79iZhXGDWQk146Z5og7-ceqKJ4Vqx9MI',
    appId: '1:708036236287:web:7ce252f6d8ab1ec9874dca',
    messagingSenderId: '708036236287',
    projectId: 'edium-93d57',
    authDomain: 'edium-93d57.firebaseapp.com',
    storageBucket: 'edium-93d57.firebasestorage.app',
    measurementId: 'G-601GXCG2PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc63Hth-E90WjOpZx4ygL20a7RrhuGpA4',
    appId: '1:708036236287:android:1b3fc173a1e3c78f874dca',
    messagingSenderId: '708036236287',
    projectId: 'edium-93d57',
    storageBucket: 'edium-93d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGQtS7c7IyGhENnqZ6czYRGonZRRPJo0',
    appId: '1:708036236287:ios:e7e5e7508bd78ac4874dca',
    messagingSenderId: '708036236287',
    projectId: 'edium-93d57',
    storageBucket: 'edium-93d57.firebasestorage.app',
    iosBundleId: 'online.edium.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeGQtS7c7IyGhENnqZ6czYRGonZRRPJo0',
    appId: '1:708036236287:ios:55c5b31e5723af0b874dca',
    messagingSenderId: '708036236287',
    projectId: 'edium-93d57',
    storageBucket: 'edium-93d57.firebasestorage.app',
    iosBundleId: 'com.example.edium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB79iZhXGDWQk146Z5og7-ceqKJ4Vqx9MI',
    appId: '1:708036236287:web:c7788c0a7f4a7414874dca',
    messagingSenderId: '708036236287',
    projectId: 'edium-93d57',
    authDomain: 'edium-93d57.firebaseapp.com',
    storageBucket: 'edium-93d57.firebasestorage.app',
    measurementId: 'G-G7S3B4G120',
  );
}
